.TH "CallInfo" 3 "2020年 九月 8日 星期二" "Version 1.0" "lua_docment_project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CallInfo
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBStkId\fP \fBfunc\fP"
.br
.ti -1c
.RI "\fBStkId\fP \fBtop\fP"
.br
.ti -1c
.RI "struct \fBCallInfo\fP * \fBprevious\fP"
.br
.ti -1c
.RI "struct \fBCallInfo\fP * \fBnext\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      const Instruction * \fBsavedpc\fP"
.br
.ti -1c
.RI "      volatile l_signalT \fBtrap\fP"
.br
.ti -1c
.RI "      int \fBnextraargs\fP"
.br
.ti -1c
.RI "   } \fBl\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      lua_KFunction \fBk\fP"
.br
.ti -1c
.RI "      ptrdiff_t \fBold_errfunc\fP"
.br
.ti -1c
.RI "      lua_KContext \fBctx\fP"
.br
.ti -1c
.RI "   } \fBc\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   int \fBfuncidx\fP"
.br
.ti -1c
.RI "   int \fBnyield\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      unsigned short \fBftransfer\fP"
.br
.ti -1c
.RI "      unsigned short \fBntransfer\fP"
.br
.ti -1c
.RI "   } \fBtransferinfo\fP"
.br
.ti -1c
.RI "} \fBu2\fP"
.br
.ti -1c
.RI "short \fBnresults\fP"
.br
.ti -1c
.RI "unsigned short \fBcallstatus\fP"
.br
.in -1c

.SH "作者"
.PP 
由 Doyxgen 通过分析 lua_docment_project 的 源代码自动生成\&.
