.TH "FuncState" 3 "2020年 九月 8日 星期二" "Version 1.0" "lua_docment_project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FuncState
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBProto\fP * \fBf\fP"
.br
.ti -1c
.RI "struct \fBFuncState\fP * \fBprev\fP"
.br
.ti -1c
.RI "struct \fBLexState\fP * \fBls\fP"
.br
.ti -1c
.RI "struct \fBBlockCnt\fP * \fBbl\fP"
.br
.ti -1c
.RI "int \fBpc\fP"
.br
.ti -1c
.RI "int \fBlasttarget\fP"
.br
.ti -1c
.RI "int \fBpreviousline\fP"
.br
.ti -1c
.RI "int \fBnk\fP"
.br
.ti -1c
.RI "int \fBnp\fP"
.br
.ti -1c
.RI "int \fBnabslineinfo\fP"
.br
.ti -1c
.RI "int \fBfirstlocal\fP"
.br
.ti -1c
.RI "int \fBfirstlabel\fP"
.br
.ti -1c
.RI "short \fBndebugvars\fP"
.br
.ti -1c
.RI "lu_byte \fBnactvar\fP"
.br
.ti -1c
.RI "lu_byte \fBnups\fP"
.br
.ti -1c
.RI "lu_byte \fBfreereg\fP"
.br
.ti -1c
.RI "lu_byte \fBiwthabs\fP"
.br
.ti -1c
.RI "lu_byte \fBneedclose\fP"
.br
.in -1c

.SH "作者"
.PP 
由 Doyxgen 通过分析 lua_docment_project 的 源代码自动生成\&.
