.TH "global_State" 3 "2020年 九月 8日 星期二" "Version 1.0" "lua_docment_project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
global_State
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "lua_Alloc \fBfrealloc\fP"
.br
.ti -1c
.RI "void * \fBud\fP"
.br
.ti -1c
.RI "l_mem \fBtotalbytes\fP"
.br
.ti -1c
.RI "l_mem \fBGCdebt\fP"
.br
.ti -1c
.RI "lu_mem \fBGCestimate\fP"
.br
.ti -1c
.RI "lu_mem \fBlastatomic\fP"
.br
.ti -1c
.RI "\fBstringtable\fP \fBstrt\fP"
.br
.ti -1c
.RI "\fBTValue\fP \fBl_registry\fP"
.br
.ti -1c
.RI "\fBTValue\fP \fBnilvalue\fP"
.br
.ti -1c
.RI "unsigned int \fBseed\fP"
.br
.ti -1c
.RI "lu_byte \fBcurrentwhite\fP"
.br
.ti -1c
.RI "lu_byte \fBgcstate\fP"
.br
.ti -1c
.RI "lu_byte \fBgckind\fP"
.br
.ti -1c
.RI "lu_byte \fBgenminormul\fP"
.br
.ti -1c
.RI "lu_byte \fBgenmajormul\fP"
.br
.ti -1c
.RI "lu_byte \fBgcrunning\fP"
.br
.ti -1c
.RI "lu_byte \fBgcemergency\fP"
.br
.ti -1c
.RI "lu_byte \fBgcpause\fP"
.br
.ti -1c
.RI "lu_byte \fBgcstepmul\fP"
.br
.ti -1c
.RI "lu_byte \fBgcstepsize\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBallgc\fP"
.br
.ti -1c
.RI "\fBGCObject\fP ** \fBsweepgc\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBfinobj\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBgray\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBgrayagain\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBweak\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBephemeron\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBallweak\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBtobefnz\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBfixedgc\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBsurvival\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBold1\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBreallyold\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBfirstold1\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBfinobjsur\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBfinobjold1\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBfinobjrold\fP"
.br
.ti -1c
.RI "struct \fBlua_State\fP * \fBtwups\fP"
.br
.ti -1c
.RI "lua_CFunction \fBpanic\fP"
.br
.ti -1c
.RI "struct \fBlua_State\fP * \fBmainthread\fP"
.br
.ti -1c
.RI "\fBTString\fP * \fBmemerrmsg\fP"
.br
.ti -1c
.RI "\fBTString\fP * \fBtmname\fP [TM_N]"
.br
.ti -1c
.RI "struct \fBTable\fP * \fBmt\fP [LUA_NUMTAGS]"
.br
.ti -1c
.RI "\fBTString\fP * \fBstrcache\fP [STRCACHE_N][STRCACHE_M]"
.br
.ti -1c
.RI "lua_WarnFunction \fBwarnf\fP"
.br
.ti -1c
.RI "void * \fBud_warn\fP"
.br
.ti -1c
.RI "unsigned int \fBCstacklimit\fP"
.br
.in -1c

.SH "作者"
.PP 
由 Doyxgen 通过分析 lua_docment_project 的 源代码自动生成\&.
