.TH "Header" 3 "2020年 九月 8日 星期二" "Version 1.0" "lua_docment_project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Header
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBlua_State\fP * \fBL\fP"
.br
.ti -1c
.RI "int \fBislittle\fP"
.br
.ti -1c
.RI "int \fBmaxalign\fP"
.br
.in -1c

.SH "作者"
.PP 
由 Doyxgen 通过分析 lua_docment_project 的 源代码自动生成\&.
