.TH "lua_State" 3 "2020年 九月 8日 星期二" "Version 1.0" "lua_docment_project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lua_State
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBCommonHeader\fP"
.br
.ti -1c
.RI "lu_byte \fBstatus\fP"
.br
.ti -1c
.RI "lu_byte \fBallowhook\fP"
.br
.ti -1c
.RI "unsigned short \fBnci\fP"
.br
.ti -1c
.RI "\fBStkId\fP \fBtop\fP"
.br
.ti -1c
.RI "\fBglobal_State\fP * \fBl_G\fP"
.br
.ti -1c
.RI "\fBCallInfo\fP * \fBci\fP"
.br
.ti -1c
.RI "\fBStkId\fP \fBstack_last\fP"
.br
.ti -1c
.RI "\fBStkId\fP \fBstack\fP"
.br
.ti -1c
.RI "\fBUpVal\fP * \fBopenupval\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBgclist\fP"
.br
.ti -1c
.RI "struct \fBlua_State\fP * \fBtwups\fP"
.br
.ti -1c
.RI "struct \fBlua_longjmp\fP * \fBerrorJmp\fP"
.br
.ti -1c
.RI "\fBCallInfo\fP \fBbase_ci\fP"
.br
.ti -1c
.RI "volatile lua_Hook \fBhook\fP"
.br
.ti -1c
.RI "ptrdiff_t \fBerrfunc\fP"
.br
.ti -1c
.RI "l_uint32 \fBnCcalls\fP"
.br
.ti -1c
.RI "int \fBoldpc\fP"
.br
.ti -1c
.RI "int \fBstacksize\fP"
.br
.ti -1c
.RI "int \fBbasehookcount\fP"
.br
.ti -1c
.RI "int \fBhookcount\fP"
.br
.ti -1c
.RI "volatile l_signalT \fBhookmask\fP"
.br
.in -1c

.SH "作者"
.PP 
由 Doyxgen 通过分析 lua_docment_project 的 源代码自动生成\&.
