.TH "lua_Debug" 3 "2020年 九月 8日 星期二" "Version 1.0" "lua_docment_project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lua_Debug
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "int \fBevent\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBnamewhat\fP"
.br
.ti -1c
.RI "const char * \fBwhat\fP"
.br
.ti -1c
.RI "const char * \fBsource\fP"
.br
.ti -1c
.RI "size_t \fBsrclen\fP"
.br
.ti -1c
.RI "int \fBcurrentline\fP"
.br
.ti -1c
.RI "int \fBlinedefined\fP"
.br
.ti -1c
.RI "int \fBlastlinedefined\fP"
.br
.ti -1c
.RI "unsigned char \fBnups\fP"
.br
.ti -1c
.RI "unsigned char \fBnparams\fP"
.br
.ti -1c
.RI "char \fBisvararg\fP"
.br
.ti -1c
.RI "char \fBistailcall\fP"
.br
.ti -1c
.RI "unsigned short \fBftransfer\fP"
.br
.ti -1c
.RI "unsigned short \fBntransfer\fP"
.br
.ti -1c
.RI "char \fBshort_src\fP [LUA_IDSIZE]"
.br
.ti -1c
.RI "struct \fBCallInfo\fP * \fBi_ci\fP"
.br
.in -1c

.SH "作者"
.PP 
由 Doyxgen 通过分析 lua_docment_project 的 源代码自动生成\&.
