.TH "Memcontrol" 3 "2020年 九月 8日 星期二" "Version 1.0" "lua_docment_project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Memcontrol
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "int \fBfailnext\fP"
.br
.ti -1c
.RI "unsigned long \fBnumblocks\fP"
.br
.ti -1c
.RI "unsigned long \fBtotal\fP"
.br
.ti -1c
.RI "unsigned long \fBmaxmem\fP"
.br
.ti -1c
.RI "unsigned long \fBmemlimit\fP"
.br
.ti -1c
.RI "unsigned long \fBcountlimit\fP"
.br
.ti -1c
.RI "unsigned long \fBobjcount\fP [LUA_NUMTYPES]"
.br
.in -1c

.SH "作者"
.PP 
由 Doyxgen 通过分析 lua_docment_project 的 源代码自动生成\&.
