.TH "SParser" 3 "2020年 九月 8日 星期二" "Version 1.0" "lua_docment_project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SParser
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBZIO\fP * \fBz\fP"
.br
.ti -1c
.RI "\fBMbuffer\fP \fBbuff\fP"
.br
.ti -1c
.RI "\fBDyndata\fP \fBdyd\fP"
.br
.ti -1c
.RI "const char * \fBmode\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.in -1c

.SH "作者"
.PP 
由 Doyxgen 通过分析 lua_docment_project 的 源代码自动生成\&.
