.TH "stringtable" 3 "2020年 九月 8日 星期二" "Version 1.0" "lua_docment_project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stringtable
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBTString\fP ** \fBhash\fP"
.br
.ti -1c
.RI "int \fBnuse\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c

.SH "作者"
.PP 
由 Doyxgen 通过分析 lua_docment_project 的 源代码自动生成\&.
