.TH "Table" 3 "2020年 九月 8日 星期二" "Version 1.0" "lua_docment_project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Table
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBCommonHeader\fP"
.br
.ti -1c
.RI "lu_byte \fBflags\fP"
.br
.ti -1c
.RI "lu_byte \fBlsizenode\fP"
.br
.ti -1c
.RI "unsigned int \fBalimit\fP"
.br
.ti -1c
.RI "\fBTValue\fP * \fBarray\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBnode\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBlastfree\fP"
.br
.ti -1c
.RI "struct \fBTable\fP * \fBmetatable\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBgclist\fP"
.br
.in -1c

.SH "作者"
.PP 
由 Doyxgen 通过分析 lua_docment_project 的 源代码自动生成\&.
