.TH "TString" 3 "2020年 九月 8日 星期二" "Version 1.0" "lua_docment_project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TString
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBCommonHeader\fP"
.br
.ti -1c
.RI "lu_byte \fBextra\fP"
.br
.ti -1c
.RI "lu_byte \fBshrlen\fP"
.br
.ti -1c
.RI "unsigned int \fBhash\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   size_t \fBlnglen\fP"
.br
.ti -1c
.RI "   struct \fBTString\fP * \fBhnext\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.ti -1c
.RI "char \fBcontents\fP [1]"
.br
.in -1c

.SH "作者"
.PP 
由 Doyxgen 通过分析 lua_docment_project 的 源代码自动生成\&.
