.TH "UpVal" 3 "2020年 九月 8日 星期二" "Version 1.0" "lua_docment_project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UpVal
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBCommonHeader\fP"
.br
.ti -1c
.RI "lu_byte \fBtbc\fP"
.br
.ti -1c
.RI "\fBTValue\fP * \fBv\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      struct \fBUpVal\fP * \fBnext\fP"
.br
.ti -1c
.RI "      struct \fBUpVal\fP ** \fBprevious\fP"
.br
.ti -1c
.RI "   } \fBopen\fP"
.br
.ti -1c
.RI "   \fBTValue\fP \fBvalue\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.in -1c

.SH "作者"
.PP 
由 Doyxgen 通过分析 lua_docment_project 的 源代码自动生成\&.
