.TH "Vardesc" 3 "2020年 九月 8日 星期二" "Version 1.0" "lua_docment_project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vardesc
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBTValuefields\fP"
.br
.ti -1c
.RI "   lu_byte \fBkind\fP"
.br
.ti -1c
.RI "   lu_byte \fBsidx\fP"
.br
.ti -1c
.RI "   short \fBpidx\fP"
.br
.ti -1c
.RI "   \fBTString\fP * \fBname\fP"
.br
.ti -1c
.RI "} \fBvd\fP"
.br
.ti -1c
.RI "\fBTValue\fP \fBk\fP"
.br
.in -1c

.SH "作者"
.PP 
由 Doyxgen 通过分析 lua_docment_project 的 源代码自动生成\&.
