.TH "BlockCnt" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockCnt
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "struct \fBBlockCnt\fP * \fBprevious\fP"
.br
.ti -1c
.RI "int \fBfirstlabel\fP"
.br
.ti -1c
.RI "int \fBfirstgoto\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBnactvar\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBupval\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBisloop\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBinsidetbc\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lparser\&.c 第 49 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "int firstgoto"

.PP
在文件 lparser\&.c 第 52 行定义\&.
.SS "int firstlabel"

.PP
在文件 lparser\&.c 第 51 行定义\&.
.SS "\fBlu_byte\fP insidetbc"

.PP
在文件 lparser\&.c 第 56 行定义\&.
.SS "\fBlu_byte\fP isloop"

.PP
在文件 lparser\&.c 第 55 行定义\&.
.SS "\fBlu_byte\fP nactvar"

.PP
在文件 lparser\&.c 第 53 行定义\&.
.SS "struct \fBBlockCnt\fP* previous"

.PP
在文件 lparser\&.c 第 50 行定义\&.
.SS "\fBlu_byte\fP upval"

.PP
在文件 lparser\&.c 第 54 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
