.TH "BuffFS" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BuffFS
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBlua_State\fP * \fBL\fP"
.br
.ti -1c
.RI "int \fBpushed\fP"
.br
.ti -1c
.RI "int \fBblen\fP"
.br
.ti -1c
.RI "char \fBspace\fP [\fBBUFVFS\fP]"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lobject\&.c 第 381 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "int blen"

.PP
在文件 lobject\&.c 第 384 行定义\&.
.SS "\fBlua_State\fP* L"

.PP
在文件 lobject\&.c 第 382 行定义\&.
.SS "int pushed"

.PP
在文件 lobject\&.c 第 383 行定义\&.
.SS "char space[\fBBUFVFS\fP]"

.PP
在文件 lobject\&.c 第 385 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
