.TH "CallS" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CallS
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBStkId\fP \fBfunc\fP"
.br
.ti -1c
.RI "int \fBnresults\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lapi\&.c 第 989 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "\fBStkId\fP func"

.PP
在文件 lapi\&.c 第 990 行定义\&.
.SS "int nresults"

.PP
在文件 lapi\&.c 第 991 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
