.TH "CClosure" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CClosure
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lobject\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBClosureHeader\fP"
.br
.ti -1c
.RI "\fBlua_CFunction\fP \fBf\fP"
.br
.ti -1c
.RI "\fBTValue\fP \fBupvalue\fP [1]"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lobject\&.h 第 621 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "ClosureHeader"

.PP
在文件 lobject\&.h 第 622 行定义\&.
.SS "\fBlua_CFunction\fP f"

.PP
在文件 lobject\&.h 第 623 行定义\&.
.SS "\fBTValue\fP upvalue[1]"

.PP
在文件 lobject\&.h 第 624 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
