.TH "FuncState" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FuncState
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lparser\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBProto\fP * \fBf\fP"
.br
.ti -1c
.RI "struct \fBFuncState\fP * \fBprev\fP"
.br
.ti -1c
.RI "struct \fBLexState\fP * \fBls\fP"
.br
.ti -1c
.RI "struct \fBBlockCnt\fP * \fBbl\fP"
.br
.ti -1c
.RI "int \fBpc\fP"
.br
.ti -1c
.RI "int \fBlasttarget\fP"
.br
.ti -1c
.RI "int \fBpreviousline\fP"
.br
.ti -1c
.RI "int \fBnk\fP"
.br
.ti -1c
.RI "int \fBnp\fP"
.br
.ti -1c
.RI "int \fBnabslineinfo\fP"
.br
.ti -1c
.RI "int \fBfirstlocal\fP"
.br
.ti -1c
.RI "int \fBfirstlabel\fP"
.br
.ti -1c
.RI "short \fBndebugvars\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBnactvar\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBnups\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBfreereg\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBiwthabs\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBneedclose\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lparser\&.h 第 143 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "struct \fBBlockCnt\fP* bl"

.PP
在文件 lparser\&.h 第 147 行定义\&.
.SS "\fBProto\fP* f"

.PP
在文件 lparser\&.h 第 144 行定义\&.
.SS "int firstlabel"

.PP
在文件 lparser\&.h 第 155 行定义\&.
.SS "int firstlocal"

.PP
在文件 lparser\&.h 第 154 行定义\&.
.SS "\fBlu_byte\fP freereg"

.PP
在文件 lparser\&.h 第 159 行定义\&.
.SS "\fBlu_byte\fP iwthabs"

.PP
在文件 lparser\&.h 第 160 行定义\&.
.SS "int lasttarget"

.PP
在文件 lparser\&.h 第 149 行定义\&.
.SS "struct \fBLexState\fP* ls"

.PP
在文件 lparser\&.h 第 146 行定义\&.
.SS "int nabslineinfo"

.PP
在文件 lparser\&.h 第 153 行定义\&.
.SS "\fBlu_byte\fP nactvar"

.PP
在文件 lparser\&.h 第 157 行定义\&.
.SS "short ndebugvars"

.PP
在文件 lparser\&.h 第 156 行定义\&.
.SS "\fBlu_byte\fP needclose"

.PP
在文件 lparser\&.h 第 161 行定义\&.
.SS "int nk"

.PP
在文件 lparser\&.h 第 151 行定义\&.
.SS "int np"

.PP
在文件 lparser\&.h 第 152 行定义\&.
.SS "\fBlu_byte\fP nups"

.PP
在文件 lparser\&.h 第 158 行定义\&.
.SS "int pc"

.PP
在文件 lparser\&.h 第 148 行定义\&.
.SS "struct \fBFuncState\fP* prev"

.PP
在文件 lparser\&.h 第 145 行定义\&.
.SS "int previousline"

.PP
在文件 lparser\&.h 第 150 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
