.TH "GCUnion" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GCUnion
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lstate\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBGCObject\fP \fBgc\fP"
.br
.ti -1c
.RI "struct \fBTString\fP \fBts\fP"
.br
.ti -1c
.RI "struct \fBUdata\fP \fBu\fP"
.br
.ti -1c
.RI "union \fBClosure\fP \fBcl\fP"
.br
.ti -1c
.RI "struct \fBTable\fP \fBh\fP"
.br
.ti -1c
.RI "struct \fBProto\fP \fBp\fP"
.br
.ti -1c
.RI "struct \fBlua_State\fP \fBth\fP"
.br
.ti -1c
.RI "struct \fBUpVal\fP \fBupv\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lstate\&.h 第 316 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "union \fBClosure\fP cl"

.PP
在文件 lstate\&.h 第 317 行定义\&.
.SS "\fBGCObject\fP gc"

.PP
在文件 lstate\&.h 第 317 行定义\&.
.SS "struct \fBTable\fP h"

.PP
在文件 lstate\&.h 第 317 行定义\&.
.SS "struct \fBProto\fP p"

.PP
在文件 lstate\&.h 第 317 行定义\&.
.SS "struct \fBlua_State\fP th"

.PP
在文件 lstate\&.h 第 317 行定义\&.
.SS "struct \fBTString\fP ts"

.PP
在文件 lstate\&.h 第 317 行定义\&.
.SS "struct \fBUdata\fP u"

.PP
在文件 lstate\&.h 第 317 行定义\&.
.SS "struct \fBUpVal\fP upv"

.PP
在文件 lstate\&.h 第 317 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
