.TH "global_State" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
global_State
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lstate\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBlua_Alloc\fP \fBfrealloc\fP"
.br
.ti -1c
.RI "void * \fBud\fP"
.br
.ti -1c
.RI "\fBl_mem\fP \fBtotalbytes\fP"
.br
.ti -1c
.RI "\fBl_mem\fP \fBGCdebt\fP"
.br
.ti -1c
.RI "\fBlu_mem\fP \fBGCestimate\fP"
.br
.ti -1c
.RI "\fBlu_mem\fP \fBlastatomic\fP"
.br
.ti -1c
.RI "\fBstringtable\fP \fBstrt\fP"
.br
.ti -1c
.RI "\fBTValue\fP \fBl_registry\fP"
.br
.ti -1c
.RI "\fBTValue\fP \fBnilvalue\fP"
.br
.ti -1c
.RI "unsigned int \fBseed\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBcurrentwhite\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBgcstate\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBgckind\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBgenminormul\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBgenmajormul\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBgcrunning\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBgcemergency\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBgcpause\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBgcstepmul\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBgcstepsize\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBallgc\fP"
.br
.ti -1c
.RI "\fBGCObject\fP ** \fBsweepgc\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBfinobj\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBgray\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBgrayagain\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBweak\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBephemeron\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBallweak\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBtobefnz\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBfixedgc\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBsurvival\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBold\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBreallyold\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBfinobjsur\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBfinobjold\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBfinobjrold\fP"
.br
.ti -1c
.RI "struct \fBlua_State\fP * \fBtwups\fP"
.br
.ti -1c
.RI "\fBlua_CFunction\fP \fBpanic\fP"
.br
.ti -1c
.RI "struct \fBlua_State\fP * \fBmainthread\fP"
.br
.ti -1c
.RI "\fBTString\fP * \fBmemerrmsg\fP"
.br
.ti -1c
.RI "\fBTString\fP * \fBtmname\fP [\fBTM_N\fP]"
.br
.ti -1c
.RI "struct \fBTable\fP * \fBmt\fP [\fBLUA_NUMTAGS\fP]"
.br
.ti -1c
.RI "\fBTString\fP * \fBstrcache\fP [\fBSTRCACHE_N\fP][\fBSTRCACHE_M\fP]"
.br
.ti -1c
.RI "\fBlua_WarnFunction\fP \fBwarnf\fP"
.br
.ti -1c
.RI "void * \fBud_warn\fP"
.br
.ti -1c
.RI "unsigned int \fBCstacklimit\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lstate\&.h 第 230 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "\fBGCObject\fP* allgc"

.PP
在文件 lstate\&.h 第 251 行定义\&.
.SS "\fBGCObject\fP* allweak"

.PP
在文件 lstate\&.h 第 258 行定义\&.
.SS "unsigned int Cstacklimit"

.PP
在文件 lstate\&.h 第 277 行定义\&.
.SS "\fBlu_byte\fP currentwhite"

.PP
在文件 lstate\&.h 第 241 行定义\&.
.SS "\fBGCObject\fP* ephemeron"

.PP
在文件 lstate\&.h 第 257 行定义\&.
.SS "\fBGCObject\fP* finobj"

.PP
在文件 lstate\&.h 第 253 行定义\&.
.SS "\fBGCObject\fP* finobjold"

.PP
在文件 lstate\&.h 第 266 行定义\&.
.SS "\fBGCObject\fP* finobjrold"

.PP
在文件 lstate\&.h 第 267 行定义\&.
.SS "\fBGCObject\fP* finobjsur"

.PP
在文件 lstate\&.h 第 265 行定义\&.
.SS "\fBGCObject\fP* fixedgc"

.PP
在文件 lstate\&.h 第 260 行定义\&.
.SS "\fBlua_Alloc\fP frealloc"

.PP
在文件 lstate\&.h 第 231 行定义\&.
.SS "\fBl_mem\fP GCdebt"

.PP
在文件 lstate\&.h 第 234 行定义\&.
.SS "\fBlu_byte\fP gcemergency"

.PP
在文件 lstate\&.h 第 247 行定义\&.
.SS "\fBlu_mem\fP GCestimate"

.PP
在文件 lstate\&.h 第 235 行定义\&.
.SS "\fBlu_byte\fP gckind"

.PP
在文件 lstate\&.h 第 243 行定义\&.
.SS "\fBlu_byte\fP gcpause"

.PP
在文件 lstate\&.h 第 248 行定义\&.
.SS "\fBlu_byte\fP gcrunning"

.PP
在文件 lstate\&.h 第 246 行定义\&.
.SS "\fBlu_byte\fP gcstate"

.PP
在文件 lstate\&.h 第 242 行定义\&.
.SS "\fBlu_byte\fP gcstepmul"

.PP
在文件 lstate\&.h 第 249 行定义\&.
.SS "\fBlu_byte\fP gcstepsize"

.PP
在文件 lstate\&.h 第 250 行定义\&.
.SS "\fBlu_byte\fP genmajormul"

.PP
在文件 lstate\&.h 第 245 行定义\&.
.SS "\fBlu_byte\fP genminormul"

.PP
在文件 lstate\&.h 第 244 行定义\&.
.SS "\fBGCObject\fP* gray"

.PP
在文件 lstate\&.h 第 254 行定义\&.
.SS "\fBGCObject\fP* grayagain"

.PP
在文件 lstate\&.h 第 255 行定义\&.
.SS "\fBTValue\fP l_registry"

.PP
在文件 lstate\&.h 第 238 行定义\&.
.SS "\fBlu_mem\fP lastatomic"

.PP
在文件 lstate\&.h 第 236 行定义\&.
.SS "struct \fBlua_State\fP* mainthread"

.PP
在文件 lstate\&.h 第 270 行定义\&.
.SS "\fBTString\fP* memerrmsg"

.PP
在文件 lstate\&.h 第 271 行定义\&.
.SS "struct \fBTable\fP* mt[\fBLUA_NUMTAGS\fP]"

.PP
在文件 lstate\&.h 第 273 行定义\&.
.SS "\fBTValue\fP nilvalue"

.PP
在文件 lstate\&.h 第 239 行定义\&.
.SS "\fBGCObject\fP* old"

.PP
在文件 lstate\&.h 第 263 行定义\&.
.SS "\fBlua_CFunction\fP panic"

.PP
在文件 lstate\&.h 第 269 行定义\&.
.SS "\fBGCObject\fP* reallyold"

.PP
在文件 lstate\&.h 第 264 行定义\&.
.SS "unsigned int seed"

.PP
在文件 lstate\&.h 第 240 行定义\&.
.SS "\fBTString\fP* strcache[\fBSTRCACHE_N\fP][\fBSTRCACHE_M\fP]"

.PP
在文件 lstate\&.h 第 274 行定义\&.
.SS "\fBstringtable\fP strt"

.PP
在文件 lstate\&.h 第 237 行定义\&.
.SS "\fBGCObject\fP* survival"

.PP
在文件 lstate\&.h 第 262 行定义\&.
.SS "\fBGCObject\fP** sweepgc"

.PP
在文件 lstate\&.h 第 252 行定义\&.
.SS "\fBTString\fP* tmname[\fBTM_N\fP]"

.PP
在文件 lstate\&.h 第 272 行定义\&.
.SS "\fBGCObject\fP* tobefnz"

.PP
在文件 lstate\&.h 第 259 行定义\&.
.SS "\fBl_mem\fP totalbytes"

.PP
在文件 lstate\&.h 第 233 行定义\&.
.SS "struct \fBlua_State\fP* twups"

.PP
在文件 lstate\&.h 第 268 行定义\&.
.SS "void* ud"

.PP
在文件 lstate\&.h 第 232 行定义\&.
.SS "void* ud_warn"

.PP
在文件 lstate\&.h 第 276 行定义\&.
.SS "\fBlua_WarnFunction\fP warnf"

.PP
在文件 lstate\&.h 第 275 行定义\&.
.SS "\fBGCObject\fP* weak"

.PP
在文件 lstate\&.h 第 256 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
