.TH "GMatchState" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GMatchState
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "const char * \fBsrc\fP"
.br
.ti -1c
.RI "const char * \fBp\fP"
.br
.ti -1c
.RI "const char * \fBlastmatch\fP"
.br
.ti -1c
.RI "\fBMatchState\fP \fBms\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lstrlib\&.c 第 827 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "const char* lastmatch"

.PP
在文件 lstrlib\&.c 第 830 行定义\&.
.SS "\fBMatchState\fP ms"

.PP
在文件 lstrlib\&.c 第 831 行定义\&.
.SS "const char* p"

.PP
在文件 lstrlib\&.c 第 829 行定义\&.
.SS "const char* src"

.PP
在文件 lstrlib\&.c 第 828 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
