.TH "Labeldesc" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Labeldesc
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lparser\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBTString\fP * \fBname\fP"
.br
.ti -1c
.RI "int \fBpc\fP"
.br
.ti -1c
.RI "int \fBline\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBnactvar\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBclose\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lparser\&.h 第 109 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "\fBlu_byte\fP close"

.PP
在文件 lparser\&.h 第 114 行定义\&.
.SS "int line"

.PP
在文件 lparser\&.h 第 112 行定义\&.
.SS "\fBlu_byte\fP nactvar"

.PP
在文件 lparser\&.h 第 113 行定义\&.
.SS "\fBTString\fP* name"

.PP
在文件 lparser\&.h 第 110 行定义\&.
.SS "int pc"

.PP
在文件 lparser\&.h 第 111 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
