.TH "C:/Users/longyg/Documents/gitprojects/lua/src/lapi.h" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/longyg/Documents/gitprojects/lua/src/lapi.h
.SH SYNOPSIS
.br
.PP
\fC#include 'llimits\&.h'\fP
.br
\fC#include 'lstate\&.h'\fP
.br

.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBapi_incr_top\fP(L)"
.br
.ti -1c
.RI "#define \fBadjustresults\fP(L,  nres)       { if ((nres) <= \fBLUA_MULTRET\fP && L\->ci\->top < L\->top) L\->ci\->top = L\->top; }"
.br
.ti -1c
.RI "#define \fBapi_checknelems\fP(L,  n)"
.br
.ti -1c
.RI "#define \fBhastocloseCfunc\fP(n)   ((n) < \fBLUA_MULTRET\fP)"
.br
.ti -1c
.RI "#define \fBcodeNresults\fP(n)   (\-(n) \- 3)"
.br
.in -1c
.SH "详细描述"
.PP 

.PP
\fB注解\fP
.RS 4
Auxiliary functions from Lua API 
.RE
.PP
\fB参见\fP
.RS 4
Copyright Notice in \fBlua\&.h\fP 
.RE
.PP

.PP
在文件 \fBlapi\&.h\fP 中定义\&.
.SH "宏定义说明"
.PP 
.SS "#define adjustresults(L, nres)       { if ((nres) <= \fBLUA_MULTRET\fP && L\->ci\->top < L\->top) L\->ci\->top = L\->top; }"

.PP
在文件 lapi\&.h 第 27 行定义\&.
.SS "#define api_checknelems(L, n)"
\fB值:\fP
.PP
.nf
               api_check(L, (n) < (L->top - L->ci->func), \
                  "not enough elements in the stack")
.fi
.PP
在文件 lapi\&.h 第 32 行定义\&.
.SS "#define api_incr_top(L)"
\fB值:\fP
.PP
.nf
              {L->top++; api_check(L, L->top <= L->ci->top, \
                "stack overflow");}
.fi
.PP
在文件 lapi\&.h 第 18 行定义\&.
.SS "#define codeNresults(n)   (\-(n) \- 3)"

.PP
在文件 lapi\&.h 第 47 行定义\&.
.SS "#define hastocloseCfunc(n)   ((n) < \fBLUA_MULTRET\fP)"

.PP
在文件 lapi\&.h 第 45 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
