.TH "LClosure" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LClosure
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lobject\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBClosureHeader\fP"
.br
.ti -1c
.RI "struct \fBProto\fP * \fBp\fP"
.br
.ti -1c
.RI "\fBUpVal\fP * \fBupvals\fP [1]"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lobject\&.h 第 628 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "ClosureHeader"

.PP
在文件 lobject\&.h 第 629 行定义\&.
.SS "struct \fBProto\fP* p"

.PP
在文件 lobject\&.h 第 630 行定义\&.
.SS "\fBUpVal\fP* upvals[1]"

.PP
在文件 lobject\&.h 第 631 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
