.TH "C:/Users/longyg/Documents/gitprojects/lua/src/lctype.c" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/longyg/Documents/gitprojects/lua/src/lctype.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lprefix\&.h'\fP
.br
\fC#include 'lctype\&.h'\fP
.br
\fC#include <limits\&.h>\fP
.br

.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBlctype_c\fP"
.br
.ti -1c
.RI "#define \fBLUA_CORE\fP"
.br
.ti -1c
.RI "#define \fBNONA\fP   0x00	/* default */"
.br
.in -1c
.SS "变量"

.in +1c
.ti -1c
.RI "\fBLUAI_DDEF\fP const \fBlu_byte\fP \fBluai_ctype_\fP [UCHAR_MAX+2]"
.br
.in -1c
.SH "宏定义说明"
.PP 
.SS "#define lctype_c"

.PP
在文件 lctype\&.c 第 7 行定义\&.
.SS "#define LUA_CORE"

.PP
在文件 lctype\&.c 第 8 行定义\&.
.SS "#define NONA   0x00	/* default */"

.PP
在文件 lctype\&.c 第 24 行定义\&.
.SH "变量说明"
.PP 
.SS "\fBLUAI_DDEF\fP const \fBlu_byte\fP luai_ctype_[UCHAR_MAX+2]"

.PP
在文件 lctype\&.c 第 28 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
