.TH "C:/Users/longyg/Documents/gitprojects/lua/src/lctype.h" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/longyg/Documents/gitprojects/lua/src/lctype.h
.SH SYNOPSIS
.br
.PP
\fC#include 'lua\&.h'\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include 'llimits\&.h'\fP
.br

.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBLUA_USE_CTYPE\fP   0"
.br
.ti -1c
.RI "#define \fBALPHABIT\fP   0"
.br
.ti -1c
.RI "#define \fBDIGITBIT\fP   1"
.br
.ti -1c
.RI "#define \fBPRINTBIT\fP   2"
.br
.ti -1c
.RI "#define \fBSPACEBIT\fP   3"
.br
.ti -1c
.RI "#define \fBXDIGITBIT\fP   4"
.br
.ti -1c
.RI "#define \fBMASK\fP(B)   (1 << (B))"
.br
.ti -1c
.RI "#define \fBtestprop\fP(c,  p)   (\fBluai_ctype_\fP[(c)+1] & (p))"
.br
.ti -1c
.RI "#define \fBlislalpha\fP(c)   \fBtestprop\fP(c, \fBMASK\fP(\fBALPHABIT\fP))"
.br
.ti -1c
.RI "#define \fBlislalnum\fP(c)   \fBtestprop\fP(c, (\fBMASK\fP(\fBALPHABIT\fP) | \fBMASK\fP(\fBDIGITBIT\fP)))"
.br
.ti -1c
.RI "#define \fBlisdigit\fP(c)   \fBtestprop\fP(c, \fBMASK\fP(\fBDIGITBIT\fP))"
.br
.ti -1c
.RI "#define \fBlisspace\fP(c)   \fBtestprop\fP(c, \fBMASK\fP(\fBSPACEBIT\fP))"
.br
.ti -1c
.RI "#define \fBlisprint\fP(c)   \fBtestprop\fP(c, \fBMASK\fP(\fBPRINTBIT\fP))"
.br
.ti -1c
.RI "#define \fBlisxdigit\fP(c)   \fBtestprop\fP(c, \fBMASK\fP(\fBXDIGITBIT\fP))"
.br
.ti -1c
.RI "#define \fBltolower\fP(c)   ((c) | ('A' ^ 'a'))"
.br
.in -1c
.SH "宏定义说明"
.PP 
.SS "#define ALPHABIT   0"

.PP
在文件 lctype\&.h 第 39 行定义\&.
.SS "#define DIGITBIT   1"

.PP
在文件 lctype\&.h 第 40 行定义\&.
.SS "#define lisdigit(c)   \fBtestprop\fP(c, \fBMASK\fP(\fBDIGITBIT\fP))"

.PP
在文件 lctype\&.h 第 59 行定义\&.
.SS "#define lislalnum(c)   \fBtestprop\fP(c, (\fBMASK\fP(\fBALPHABIT\fP) | \fBMASK\fP(\fBDIGITBIT\fP)))"

.PP
在文件 lctype\&.h 第 58 行定义\&.
.SS "#define lislalpha(c)   \fBtestprop\fP(c, \fBMASK\fP(\fBALPHABIT\fP))"

.PP
在文件 lctype\&.h 第 57 行定义\&.
.SS "#define lisprint(c)   \fBtestprop\fP(c, \fBMASK\fP(\fBPRINTBIT\fP))"

.PP
在文件 lctype\&.h 第 61 行定义\&.
.SS "#define lisspace(c)   \fBtestprop\fP(c, \fBMASK\fP(\fBSPACEBIT\fP))"

.PP
在文件 lctype\&.h 第 60 行定义\&.
.SS "#define lisxdigit(c)   \fBtestprop\fP(c, \fBMASK\fP(\fBXDIGITBIT\fP))"

.PP
在文件 lctype\&.h 第 62 行定义\&.
.SS "#define ltolower(c)   ((c) | ('A' ^ 'a'))"

.PP
在文件 lctype\&.h 第 67 行定义\&.
.SS "#define LUA_USE_CTYPE   0"

.PP
在文件 lctype\&.h 第 23 行定义\&.
.SS "#define MASK(B)   (1 << (B))"

.PP
在文件 lctype\&.h 第 46 行定义\&.
.SS "#define PRINTBIT   2"

.PP
在文件 lctype\&.h 第 41 行定义\&.
.SS "#define SPACEBIT   3"

.PP
在文件 lctype\&.h 第 42 行定义\&.
.SS "#define testprop(c, p)   (\fBluai_ctype_\fP[(c)+1] & (p))"

.PP
在文件 lctype\&.h 第 52 行定义\&.
.SS "#define XDIGITBIT   4"

.PP
在文件 lctype\&.h 第 43 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
