.TH "LexState" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LexState
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <llex\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "int \fBcurrent\fP"
.br
.ti -1c
.RI "int \fBlinenumber\fP"
.br
.ti -1c
.RI "int \fBlastline\fP"
.br
.ti -1c
.RI "\fBToken\fP \fBt\fP"
.br
.ti -1c
.RI "\fBToken\fP \fBlookahead\fP"
.br
.ti -1c
.RI "struct \fBFuncState\fP * \fBfs\fP"
.br
.ti -1c
.RI "struct \fBlua_State\fP * \fBL\fP"
.br
.ti -1c
.RI "\fBZIO\fP * \fBz\fP"
.br
.ti -1c
.RI "\fBMbuffer\fP * \fBbuff\fP"
.br
.ti -1c
.RI "\fBTable\fP * \fBh\fP"
.br
.ti -1c
.RI "struct \fBDyndata\fP * \fBdyd\fP"
.br
.ti -1c
.RI "\fBTString\fP * \fBsource\fP"
.br
.ti -1c
.RI "\fBTString\fP * \fBenvn\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 llex\&.h 第 58 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "\fBMbuffer\fP* buff"

.PP
在文件 llex\&.h 第 67 行定义\&.
.SS "int current"

.PP
在文件 llex\&.h 第 59 行定义\&.
.SS "struct \fBDyndata\fP* dyd"

.PP
在文件 llex\&.h 第 69 行定义\&.
.SS "\fBTString\fP* envn"

.PP
在文件 llex\&.h 第 71 行定义\&.
.SS "struct \fBFuncState\fP* fs"

.PP
在文件 llex\&.h 第 64 行定义\&.
.SS "\fBTable\fP* h"

.PP
在文件 llex\&.h 第 68 行定义\&.
.SS "struct \fBlua_State\fP* L"

.PP
在文件 llex\&.h 第 65 行定义\&.
.SS "int lastline"

.PP
在文件 llex\&.h 第 61 行定义\&.
.SS "int linenumber"

.PP
在文件 llex\&.h 第 60 行定义\&.
.SS "\fBToken\fP lookahead"

.PP
在文件 llex\&.h 第 63 行定义\&.
.SS "\fBTString\fP* source"

.PP
在文件 llex\&.h 第 70 行定义\&.
.SS "\fBToken\fP t"

.PP
在文件 llex\&.h 第 62 行定义\&.
.SS "\fBZIO\fP* z"

.PP
在文件 llex\&.h 第 66 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
