.TH "LG" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LG
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBLX\fP \fBl\fP"
.br
.ti -1c
.RI "\fBglobal_State\fP \fBg\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lstate\&.c 第 44 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "\fBglobal_State\fP g"

.PP
在文件 lstate\&.c 第 46 行定义\&.
.SS "\fBLX\fP l"

.PP
在文件 lstate\&.c 第 45 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
