.TH "D:/gitworkspace/lua/testes/libs/lib21.c" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitworkspace/lua/testes/libs/lib21.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lua\&.h'\fP
.br

.SS "函数"

.in +1c
.ti -1c
.RI "int \fBluaopen_lib2\fP (\fBlua_State\fP *L)"
.br
.ti -1c
.RI "\fBLUAMOD_API\fP int \fBluaopen_lib21\fP (\fBlua_State\fP *L)"
.br
.in -1c
.SH "函数说明"
.PP 
.SS "int luaopen_lib2 (\fBlua_State\fP * L)"

.PP
在文件 lib2\&.c 第 15 行定义\&.
.SS "\fBLUAMOD_API\fP int luaopen_lib21 (\fBlua_State\fP * L)"

.PP
在文件 lib21\&.c 第 6 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
