.TH "C:/Users/longyg/Documents/gitprojects/lua/src/ljumptab.h" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/longyg/Documents/gitprojects/lua/src/ljumptab.h
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBvmdispatch\fP(x)   goto *\fBdisptab\fP[x];"
.br
.ti -1c
.RI "#define \fBvmcase\fP(l)   L_##l:"
.br
.ti -1c
.RI "#define \fBvmbreak\fP   \fBvmfetch\fP(); \fBvmdispatch\fP(\fBGET_OPCODE\fP(i));"
.br
.in -1c
.SS "变量"

.in +1c
.ti -1c
.RI "static const void *const \fBdisptab\fP [\fBNUM_OPCODES\fP]"
.br
.in -1c
.SH "宏定义说明"
.PP 
.SS "#define vmbreak   \fBvmfetch\fP(); \fBvmdispatch\fP(\fBGET_OPCODE\fP(i));"

.PP
在文件 ljumptab\&.h 第 16 行定义\&.
.SS "#define vmcase(l)   L_##l:"

.PP
在文件 ljumptab\&.h 第 14 行定义\&.
.SS "#define vmdispatch(x)   goto *\fBdisptab\fP[x];"

.PP
在文件 ljumptab\&.h 第 12 行定义\&.
.SH "变量说明"
.PP 
.SS "const void* const disptab[\fBNUM_OPCODES\fP]\fC [static]\fP"

.PP
在文件 ljumptab\&.h 第 19 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
