.TH "LoadF" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoadF
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "FILE * \fBf\fP"
.br
.ti -1c
.RI "char \fBbuff\fP [BUFSIZ]"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lauxlib\&.c 第 684 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "char buff[BUFSIZ]"

.PP
在文件 lauxlib\&.c 第 687 行定义\&.
.SS "FILE* f"

.PP
在文件 lauxlib\&.c 第 686 行定义\&.
.SS "int n"

.PP
在文件 lauxlib\&.c 第 685 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
