.TH "LoadState" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoadState
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBlua_State\fP * \fBL\fP"
.br
.ti -1c
.RI "\fBZIO\fP * \fBZ\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lundump\&.c 第 33 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "\fBlua_State\fP* L"

.PP
在文件 lundump\&.c 第 34 行定义\&.
.SS "const char* name"

.PP
在文件 lundump\&.c 第 36 行定义\&.
.SS "\fBZIO\fP* Z"

.PP
在文件 lundump\&.c 第 35 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
