.TH "LocVar" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LocVar
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lobject\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBTString\fP * \fBvarname\fP"
.br
.ti -1c
.RI "int \fBstartpc\fP"
.br
.ti -1c
.RI "int \fBendpc\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lobject\&.h 第 502 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "int endpc"

.PP
在文件 lobject\&.h 第 505 行定义\&.
.SS "int startpc"

.PP
在文件 lobject\&.h 第 504 行定义\&.
.SS "\fBTString\fP* varname"

.PP
在文件 lobject\&.h 第 503 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
