.TH "C:/Users/longyg/Documents/gitprojects/lua/src/lopnames.h" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/longyg/Documents/gitprojects/lua/src/lopnames.h
.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br

.SS "变量"

.in +1c
.ti -1c
.RI "static const char *const \fBopnames\fP []"
.br
.in -1c
.SH "变量说明"
.PP 
.SS "const char* const opnames[]\fC [static]\fP"

.PP
在文件 lopnames\&.h 第 15 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
