.TH "C:/Users/longyg/Documents/gitprojects/lua/src/lprefix.h" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/longyg/Documents/gitprojects/lua/src/lprefix.h
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB_XOPEN_SOURCE\fP   600"
.br
.ti -1c
.RI "#define \fB_LARGEFILE_SOURCE\fP   1"
.br
.ti -1c
.RI "#define \fB_FILE_OFFSET_BITS\fP   64"
.br
.in -1c
.SH "宏定义说明"
.PP 
.SS "#define _FILE_OFFSET_BITS   64"

.PP
在文件 lprefix\&.h 第 27 行定义\&.
.SS "#define _LARGEFILE_SOURCE   1"

.PP
在文件 lprefix\&.h 第 26 行定义\&.
.SS "#define _XOPEN_SOURCE   600"

.PP
在文件 lprefix\&.h 第 17 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
