.TH "D:/gitworkspace/lua/ltests.c" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitworkspace/lua/ltests.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lprefix\&.h'\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include <setjmp\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'lua\&.h'\fP
.br
\fC#include 'lapi\&.h'\fP
.br
\fC#include 'lauxlib\&.h'\fP
.br
\fC#include 'lcode\&.h'\fP
.br
\fC#include 'lctype\&.h'\fP
.br
\fC#include 'ldebug\&.h'\fP
.br
\fC#include 'ldo\&.h'\fP
.br
\fC#include 'lfunc\&.h'\fP
.br
\fC#include 'lmem\&.h'\fP
.br
\fC#include 'lopcodes\&.h'\fP
.br
\fC#include 'lopnames\&.h'\fP
.br
\fC#include 'lstate\&.h'\fP
.br
\fC#include 'lstring\&.h'\fP
.br
\fC#include 'ltable\&.h'\fP
.br
\fC#include 'lualib\&.h'\fP
.br

.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBltests_c\fP"
.br
.ti -1c
.RI "#define \fBLUA_CORE\fP"
.br
.in -1c
.SH "宏定义说明"
.PP 
.SS "#define ltests_c"

.PP
在文件 ltests\&.c 第 7 行定义\&.
.SS "#define LUA_CORE"

.PP
在文件 ltests\&.c 第 8 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
