.TH "lua_State" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lua_State
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lstate\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBCommonHeader\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBstatus\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBallowhook\fP"
.br
.ti -1c
.RI "unsigned short \fBnci\fP"
.br
.ti -1c
.RI "\fBStkId\fP \fBtop\fP"
.br
.ti -1c
.RI "\fBglobal_State\fP * \fBl_G\fP"
.br
.ti -1c
.RI "\fBCallInfo\fP * \fBci\fP"
.br
.ti -1c
.RI "const \fBInstruction\fP * \fBoldpc\fP"
.br
.ti -1c
.RI "\fBStkId\fP \fBstack_last\fP"
.br
.ti -1c
.RI "\fBStkId\fP \fBstack\fP"
.br
.ti -1c
.RI "\fBUpVal\fP * \fBopenupval\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBgclist\fP"
.br
.ti -1c
.RI "struct \fBlua_State\fP * \fBtwups\fP"
.br
.ti -1c
.RI "struct \fBlua_longjmp\fP * \fBerrorJmp\fP"
.br
.ti -1c
.RI "\fBCallInfo\fP \fBbase_ci\fP"
.br
.ti -1c
.RI "volatile \fBlua_Hook\fP \fBhook\fP"
.br
.ti -1c
.RI "ptrdiff_t \fBerrfunc\fP"
.br
.ti -1c
.RI "\fBl_uint32\fP \fBnCcalls\fP"
.br
.ti -1c
.RI "int \fBstacksize\fP"
.br
.ti -1c
.RI "int \fBbasehookcount\fP"
.br
.ti -1c
.RI "int \fBhookcount\fP"
.br
.ti -1c
.RI "volatile \fBl_signalT\fP \fBhookmask\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lstate\&.h 第 284 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "\fBlu_byte\fP allowhook"

.PP
在文件 lstate\&.h 第 287 行定义\&.
.SS "\fBCallInfo\fP base_ci"

.PP
在文件 lstate\&.h 第 299 行定义\&.
.SS "int basehookcount"

.PP
在文件 lstate\&.h 第 304 行定义\&.
.SS "\fBCallInfo\fP* ci"

.PP
在文件 lstate\&.h 第 291 行定义\&.
.SS "CommonHeader"

.PP
在文件 lstate\&.h 第 285 行定义\&.
.SS "ptrdiff_t errfunc"

.PP
在文件 lstate\&.h 第 301 行定义\&.
.SS "struct \fBlua_longjmp\fP* errorJmp"

.PP
在文件 lstate\&.h 第 298 行定义\&.
.SS "\fBGCObject\fP* gclist"

.PP
在文件 lstate\&.h 第 296 行定义\&.
.SS "volatile \fBlua_Hook\fP hook"

.PP
在文件 lstate\&.h 第 300 行定义\&.
.SS "int hookcount"

.PP
在文件 lstate\&.h 第 305 行定义\&.
.SS "volatile \fBl_signalT\fP hookmask"

.PP
在文件 lstate\&.h 第 306 行定义\&.
.SS "\fBglobal_State\fP* l_G"

.PP
在文件 lstate\&.h 第 290 行定义\&.
.SS "\fBl_uint32\fP nCcalls"

.PP
在文件 lstate\&.h 第 302 行定义\&.
.SS "unsigned short nci"

.PP
在文件 lstate\&.h 第 288 行定义\&.
.SS "const \fBInstruction\fP* oldpc"

.PP
在文件 lstate\&.h 第 292 行定义\&.
.SS "\fBUpVal\fP* openupval"

.PP
在文件 lstate\&.h 第 295 行定义\&.
.SS "\fBStkId\fP stack"

.PP
在文件 lstate\&.h 第 294 行定义\&.
.SS "\fBStkId\fP stack_last"

.PP
在文件 lstate\&.h 第 293 行定义\&.
.SS "int stacksize"

.PP
在文件 lstate\&.h 第 303 行定义\&.
.SS "\fBlu_byte\fP status"

.PP
在文件 lstate\&.h 第 286 行定义\&.
.SS "\fBStkId\fP top"

.PP
在文件 lstate\&.h 第 289 行定义\&.
.SS "struct \fBlua_State\fP* twups"

.PP
在文件 lstate\&.h 第 297 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
