.TH "lua_Debug" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lua_Debug
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lua\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "int \fBevent\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBnamewhat\fP"
.br
.ti -1c
.RI "const char * \fBwhat\fP"
.br
.ti -1c
.RI "const char * \fBsource\fP"
.br
.ti -1c
.RI "size_t \fBsrclen\fP"
.br
.ti -1c
.RI "int \fBcurrentline\fP"
.br
.ti -1c
.RI "int \fBlinedefined\fP"
.br
.ti -1c
.RI "int \fBlastlinedefined\fP"
.br
.ti -1c
.RI "unsigned char \fBnups\fP"
.br
.ti -1c
.RI "unsigned char \fBnparams\fP"
.br
.ti -1c
.RI "char \fBisvararg\fP"
.br
.ti -1c
.RI "char \fBistailcall\fP"
.br
.ti -1c
.RI "unsigned short \fBftransfer\fP"
.br
.ti -1c
.RI "unsigned short \fBntransfer\fP"
.br
.ti -1c
.RI "char \fBshort_src\fP [\fBLUA_IDSIZE\fP]"
.br
.ti -1c
.RI "struct \fBCallInfo\fP * \fBi_ci\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lua\&.h 第 469 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "int currentline"

.PP
在文件 lua\&.h 第 476 行定义\&.
.SS "int event"

.PP
在文件 lua\&.h 第 470 行定义\&.
.SS "unsigned short ftransfer"

.PP
在文件 lua\&.h 第 483 行定义\&.
.SS "struct \fBCallInfo\fP* i_ci"

.PP
在文件 lua\&.h 第 487 行定义\&.
.SS "char istailcall"

.PP
在文件 lua\&.h 第 482 行定义\&.
.SS "char isvararg"

.PP
在文件 lua\&.h 第 481 行定义\&.
.SS "int lastlinedefined"

.PP
在文件 lua\&.h 第 478 行定义\&.
.SS "int linedefined"

.PP
在文件 lua\&.h 第 477 行定义\&.
.SS "const char* name"

.PP
在文件 lua\&.h 第 471 行定义\&.
.SS "const char* namewhat"

.PP
在文件 lua\&.h 第 472 行定义\&.
.SS "unsigned char nparams"

.PP
在文件 lua\&.h 第 480 行定义\&.
.SS "unsigned short ntransfer"

.PP
在文件 lua\&.h 第 484 行定义\&.
.SS "unsigned char nups"

.PP
在文件 lua\&.h 第 479 行定义\&.
.SS "char short_src[\fBLUA_IDSIZE\fP]"

.PP
在文件 lua\&.h 第 485 行定义\&.
.SS "const char* source"

.PP
在文件 lua\&.h 第 474 行定义\&.
.SS "size_t srclen"

.PP
在文件 lua\&.h 第 475 行定义\&.
.SS "const char* what"

.PP
在文件 lua\&.h 第 473 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
