.TH "luaL_Stream" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
luaL_Stream
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lauxlib\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "FILE * \fBf\fP"
.br
.ti -1c
.RI "\fBlua_CFunction\fP \fBclosef\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lauxlib\&.h 第 220 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "\fBlua_CFunction\fP closef"

.PP
在文件 lauxlib\&.h 第 222 行定义\&.
.SS "FILE* f"

.PP
在文件 lauxlib\&.h 第 221 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
