.TH "luaL_Buffer" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
luaL_Buffer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lauxlib\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "char * \fBb\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "size_t \fBn\fP"
.br
.ti -1c
.RI "\fBlua_State\fP * \fBL\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBLUAI_MAXALIGN\fP"
.br
.ti -1c
.RI "   char \fBb\fP [\fBLUAL_BUFFERSIZE\fP]"
.br
.ti -1c
.RI "} \fBinit\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lauxlib\&.h 第 166 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "char* b"

.PP
在文件 lauxlib\&.h 第 167 行定义\&.
.SS "char b[\fBLUAL_BUFFERSIZE\fP]"

.PP
在文件 lauxlib\&.h 第 173 行定义\&.
.SS "union { \&.\&.\&. }  init"

.SS "\fBlua_State\fP* L"

.PP
在文件 lauxlib\&.h 第 170 行定义\&.
.SS "LUAI_MAXALIGN"

.PP
在文件 lauxlib\&.h 第 172 行定义\&.
.SS "size_t n"

.PP
在文件 lauxlib\&.h 第 169 行定义\&.
.SS "size_t size"

.PP
在文件 lauxlib\&.h 第 168 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
