.TH "luaL_Reg" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
luaL_Reg
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lauxlib\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "\fBlua_CFunction\fP \fBfunc\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lauxlib\&.h 第 37 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "\fBlua_CFunction\fP func"

.PP
在文件 lauxlib\&.h 第 39 行定义\&.
.SS "const char* name"

.PP
在文件 lauxlib\&.h 第 38 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
