.TH "D:/gitworkspace/lua/src/lualib.h" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitworkspace/lua/src/lualib.h
.SH SYNOPSIS
.br
.PP
\fC#include 'lua\&.h'\fP
.br

.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBLUA_VERSUFFIX\fP   '_' LUA_VERSION_MAJOR '_' LUA_VERSION_MINOR"
.br
.ti -1c
.RI "#define \fBLUA_COLIBNAME\fP   'coroutine'"
.br
.ti -1c
.RI "#define \fBLUA_TABLIBNAME\fP   'table'"
.br
.ti -1c
.RI "#define \fBLUA_IOLIBNAME\fP   'io'"
.br
.ti -1c
.RI "#define \fBLUA_OSLIBNAME\fP   'os'"
.br
.ti -1c
.RI "#define \fBLUA_STRLIBNAME\fP   'string'"
.br
.ti -1c
.RI "#define \fBLUA_UTF8LIBNAME\fP   'utf8'"
.br
.ti -1c
.RI "#define \fBLUA_MATHLIBNAME\fP   'math'"
.br
.ti -1c
.RI "#define \fBLUA_DBLIBNAME\fP   'debug'"
.br
.ti -1c
.RI "#define \fBLUA_LOADLIBNAME\fP   'package'"
.br
.ti -1c
.RI "#define \fBlua_assert\fP(x)   ((void)0)"
.br
.in -1c
.SS "函数"

.in +1c
.ti -1c
.RI "\fBLUAMOD_API\fP int() \fBluaopen_base\fP (\fBlua_State\fP *L)"
.br
.ti -1c
.RI "\fBLUAMOD_API\fP int() \fBluaopen_coroutine\fP (\fBlua_State\fP *L)"
.br
.ti -1c
.RI "\fBLUAMOD_API\fP int() \fBluaopen_table\fP (\fBlua_State\fP *L)"
.br
.ti -1c
.RI "\fBLUAMOD_API\fP int() \fBluaopen_io\fP (\fBlua_State\fP *L)"
.br
.ti -1c
.RI "\fBLUAMOD_API\fP int() \fBluaopen_os\fP (\fBlua_State\fP *L)"
.br
.ti -1c
.RI "\fBLUAMOD_API\fP int() \fBluaopen_string\fP (\fBlua_State\fP *L)"
.br
.ti -1c
.RI "\fBLUAMOD_API\fP int() \fBluaopen_utf8\fP (\fBlua_State\fP *L)"
.br
.ti -1c
.RI "\fBLUAMOD_API\fP int() \fBluaopen_math\fP (\fBlua_State\fP *L)"
.br
.ti -1c
.RI "\fBLUAMOD_API\fP int() \fBluaopen_debug\fP (\fBlua_State\fP *L)"
.br
.ti -1c
.RI "\fBLUAMOD_API\fP int() \fBluaopen_package\fP (\fBlua_State\fP *L)"
.br
.ti -1c
.RI "\fBLUALIB_API\fP void() \fBluaL_openlibs\fP (\fBlua_State\fP *L)"
.br
.in -1c
.SH "宏定义说明"
.PP 
.SS "#define lua_assert(x)   ((void)0)"

.PP
在文件 lualib\&.h 第 54 行定义\&.
.SS "#define LUA_COLIBNAME   'coroutine'"

.PP
在文件 lualib\&.h 第 20 行定义\&.
.SS "#define LUA_DBLIBNAME   'debug'"

.PP
在文件 lualib\&.h 第 41 行定义\&.
.SS "#define LUA_IOLIBNAME   'io'"

.PP
在文件 lualib\&.h 第 26 行定义\&.
.SS "#define LUA_LOADLIBNAME   'package'"

.PP
在文件 lualib\&.h 第 44 行定义\&.
.SS "#define LUA_MATHLIBNAME   'math'"

.PP
在文件 lualib\&.h 第 38 行定义\&.
.SS "#define LUA_OSLIBNAME   'os'"

.PP
在文件 lualib\&.h 第 29 行定义\&.
.SS "#define LUA_STRLIBNAME   'string'"

.PP
在文件 lualib\&.h 第 32 行定义\&.
.SS "#define LUA_TABLIBNAME   'table'"

.PP
在文件 lualib\&.h 第 23 行定义\&.
.SS "#define LUA_UTF8LIBNAME   'utf8'"

.PP
在文件 lualib\&.h 第 35 行定义\&.
.SS "#define LUA_VERSUFFIX   '_' LUA_VERSION_MAJOR '_' LUA_VERSION_MINOR"

.PP
在文件 lualib\&.h 第 15 行定义\&.
.SH "函数说明"
.PP 
.SS "\fBLUALIB_API\fP void() luaL_openlibs (\fBlua_State\fP * L)"

.PP
在文件 linit\&.c 第 57 行定义\&.
.SS "\fBLUAMOD_API\fP int() luaopen_base (\fBlua_State\fP * L)"

.PP
在文件 lbaselib\&.c 第 515 行定义\&.
.SS "\fBLUAMOD_API\fP int() luaopen_coroutine (\fBlua_State\fP * L)"

.PP
在文件 lcorolib\&.c 第 202 行定义\&.
.SS "\fBLUAMOD_API\fP int() luaopen_debug (\fBlua_State\fP * L)"

.PP
在文件 ldblib\&.c 第 473 行定义\&.
.SS "\fBLUAMOD_API\fP int() luaopen_io (\fBlua_State\fP * L)"

.PP
在文件 liolib\&.c 第 805 行定义\&.
.SS "\fBLUAMOD_API\fP int() luaopen_math (\fBlua_State\fP * L)"

.PP
在文件 lmathlib\&.c 第 750 行定义\&.
.SS "\fBLUAMOD_API\fP int() luaopen_os (\fBlua_State\fP * L)"

.PP
在文件 loslib\&.c 第 426 行定义\&.
.SS "\fBLUAMOD_API\fP int() luaopen_package (\fBlua_State\fP * L)"

.PP
在文件 loadlib\&.c 第 736 行定义\&.
.SS "\fBLUAMOD_API\fP int() luaopen_string (\fBlua_State\fP * L)"

.PP
在文件 lstrlib\&.c 第 1800 行定义\&.
.SS "\fBLUAMOD_API\fP int() luaopen_table (\fBlua_State\fP * L)"

.PP
在文件 ltablib\&.c 第 424 行定义\&.
.SS "\fBLUAMOD_API\fP int() luaopen_utf8 (\fBlua_State\fP * L)"

.PP
在文件 lutf8lib\&.c 第 283 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
