.TH "C:/Users/longyg/Documents/gitprojects/lua/src/lundump.h" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/longyg/Documents/gitprojects/lua/src/lundump.h
.SH SYNOPSIS
.br
.PP
\fC#include 'llimits\&.h'\fP
.br
\fC#include 'lobject\&.h'\fP
.br
\fC#include 'lzio\&.h'\fP
.br

.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBLUAC_DATA\fP   '\\x19\\x93\\r\\n\\x1a\\n'"
.br
.ti -1c
.RI "#define \fBLUAC_INT\fP   0x5678"
.br
.ti -1c
.RI "#define \fBLUAC_NUM\fP   \fBcast_num\fP(370\&.5)"
.br
.ti -1c
.RI "#define \fBMYINT\fP(s)   (s[0]\-'0')  /* assume one\-\fBdigit\fP numerals */"
.br
.ti -1c
.RI "#define \fBLUAC_VERSION\fP   (\fBMYINT\fP(\fBLUA_VERSION_MAJOR\fP)*16+\fBMYINT\fP(\fBLUA_VERSION_MINOR\fP))"
.br
.ti -1c
.RI "#define \fBLUAC_FORMAT\fP   0	/* this is the official format */"
.br
.in -1c
.SS "函数"

.in +1c
.ti -1c
.RI "\fBLUAI_FUNC\fP \fBLClosure\fP * \fBluaU_undump\fP (\fBlua_State\fP *L, \fBZIO\fP *Z, const char *name)"
.br
.ti -1c
.RI "\fBLUAI_FUNC\fP int \fBluaU_dump\fP (\fBlua_State\fP *L, const \fBProto\fP *f, \fBlua_Writer\fP w, void *data, int strip)"
.br
.in -1c
.SH "宏定义说明"
.PP 
.SS "#define LUAC_DATA   '\\x19\\x93\\r\\n\\x1a\\n'"

.PP
在文件 lundump\&.h 第 16 行定义\&.
.SS "#define LUAC_FORMAT   0	/* this is the official format */"

.PP
在文件 lundump\&.h 第 27 行定义\&.
.SS "#define LUAC_INT   0x5678"

.PP
在文件 lundump\&.h 第 18 行定义\&.
.SS "#define LUAC_NUM   \fBcast_num\fP(370\&.5)"

.PP
在文件 lundump\&.h 第 19 行定义\&.
.SS "#define LUAC_VERSION   (\fBMYINT\fP(\fBLUA_VERSION_MAJOR\fP)*16+\fBMYINT\fP(\fBLUA_VERSION_MINOR\fP))"

.PP
在文件 lundump\&.h 第 25 行定义\&.
.SS "#define MYINT(s)   (s[0]\-'0')  /* assume one\-\fBdigit\fP numerals */"

.PP
在文件 lundump\&.h 第 24 行定义\&.
.SH "函数说明"
.PP 
.SS "\fBLUAI_FUNC\fP int luaU_dump (\fBlua_State\fP * L, const \fBProto\fP * f, \fBlua_Writer\fP w, void * data, int strip)"

.PP
在文件 ldump\&.c 第 213 行定义\&.
.SS "\fBLUAI_FUNC\fP \fBLClosure\fP* luaU_undump (\fBlua_State\fP * L, \fBZIO\fP * Z, const char * name)"

.PP
在文件 lundump\&.c 第 301 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
