.TH "D:/gitworkspace/lua/src/lzio.c" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitworkspace/lua/src/lzio.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lprefix\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'lua\&.h'\fP
.br
\fC#include 'llimits\&.h'\fP
.br
\fC#include 'lmem\&.h'\fP
.br
\fC#include 'lstate\&.h'\fP
.br
\fC#include 'lzio\&.h'\fP
.br

.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBlzio_c\fP"
.br
.ti -1c
.RI "#define \fBLUA_CORE\fP"
.br
.in -1c
.SS "函数"

.in +1c
.ti -1c
.RI "int \fBluaZ_fill\fP (\fBZIO\fP *z)"
.br
.ti -1c
.RI "void \fBluaZ_init\fP (\fBlua_State\fP *L, \fBZIO\fP *z, \fBlua_Reader\fP \fBreader\fP, void *data)"
.br
.ti -1c
.RI "size_t \fBluaZ_read\fP (\fBZIO\fP *z, void *b, size_t n)"
.br
.in -1c
.SH "宏定义说明"
.PP 
.SS "#define LUA_CORE"

.PP
在文件 lzio\&.c 第 8 行定义\&.
.SS "#define lzio_c"

.PP
在文件 lzio\&.c 第 7 行定义\&.
.SH "函数说明"
.PP 
.SS "int luaZ_fill (\fBZIO\fP * z)"

.PP
在文件 lzio\&.c 第 23 行定义\&.
.SS "void luaZ_init (\fBlua_State\fP * L, \fBZIO\fP * z, \fBlua_Reader\fP reader, void * data)"

.PP
在文件 lzio\&.c 第 38 行定义\&.
.SS "size_t luaZ_read (\fBZIO\fP * z, void * b, size_t n)"

.PP
在文件 lzio\&.c 第 48 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
