.TH "Mbuffer" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mbuffer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lzio\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "char * \fBbuffer\fP"
.br
.ti -1c
.RI "size_t \fBn\fP"
.br
.ti -1c
.RI "size_t \fBbuffsize\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lzio\&.h 第 23 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "char* buffer"

.PP
在文件 lzio\&.h 第 24 行定义\&.
.SS "size_t buffsize"

.PP
在文件 lzio\&.h 第 26 行定义\&.
.SS "size_t n"

.PP
在文件 lzio\&.h 第 25 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
