.TH "Memcontrol" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Memcontrol
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ltests\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "int \fBfailnext\fP"
.br
.ti -1c
.RI "unsigned long \fBnumblocks\fP"
.br
.ti -1c
.RI "unsigned long \fBtotal\fP"
.br
.ti -1c
.RI "unsigned long \fBmaxmem\fP"
.br
.ti -1c
.RI "unsigned long \fBmemlimit\fP"
.br
.ti -1c
.RI "unsigned long \fBcountlimit\fP"
.br
.ti -1c
.RI "unsigned long \fBobjcount\fP [\fBLUA_NUMTYPES\fP]"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 ltests\&.h 第 53 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "unsigned long countlimit"

.PP
在文件 ltests\&.h 第 59 行定义\&.
.SS "int failnext"

.PP
在文件 ltests\&.h 第 54 行定义\&.
.SS "unsigned long maxmem"

.PP
在文件 ltests\&.h 第 57 行定义\&.
.SS "unsigned long memlimit"

.PP
在文件 ltests\&.h 第 58 行定义\&.
.SS "unsigned long numblocks"

.PP
在文件 ltests\&.h 第 55 行定义\&.
.SS "unsigned long objcount[\fBLUA_NUMTYPES\fP]"

.PP
在文件 ltests\&.h 第 60 行定义\&.
.SS "unsigned long total"

.PP
在文件 ltests\&.h 第 56 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
