.TH "D:/gitworkspace/lua/onelua.c" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitworkspace/lua/onelua.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lprefix\&.h'\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <float\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include <locale\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <setjmp\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include 'luaconf\&.h'\fP
.br
\fC#include 'lzio\&.c'\fP
.br
\fC#include 'lctype\&.c'\fP
.br
\fC#include 'lopcodes\&.c'\fP
.br
\fC#include 'lmem\&.c'\fP
.br
\fC#include 'lundump\&.c'\fP
.br
\fC#include 'ldump\&.c'\fP
.br
\fC#include 'lstate\&.c'\fP
.br
\fC#include 'lgc\&.c'\fP
.br
\fC#include 'llex\&.c'\fP
.br
\fC#include 'lcode\&.c'\fP
.br
\fC#include 'lparser\&.c'\fP
.br
\fC#include 'ldebug\&.c'\fP
.br
\fC#include 'lfunc\&.c'\fP
.br
\fC#include 'lobject\&.c'\fP
.br
\fC#include 'ltm\&.c'\fP
.br
\fC#include 'lstring\&.c'\fP
.br
\fC#include 'ltable\&.c'\fP
.br
\fC#include 'ldo\&.c'\fP
.br
\fC#include 'lvm\&.c'\fP
.br
\fC#include 'lapi\&.c'\fP
.br
\fC#include 'lauxlib\&.c'\fP
.br
\fC#include 'lbaselib\&.c'\fP
.br
\fC#include 'lcorolib\&.c'\fP
.br
\fC#include 'ldblib\&.c'\fP
.br
\fC#include 'liolib\&.c'\fP
.br
\fC#include 'lmathlib\&.c'\fP
.br
\fC#include 'loadlib\&.c'\fP
.br
\fC#include 'loslib\&.c'\fP
.br
\fC#include 'lstrlib\&.c'\fP
.br
\fC#include 'ltablib\&.c'\fP
.br
\fC#include 'lutf8lib\&.c'\fP
.br
\fC#include 'linit\&.c'\fP
.br
\fC#include 'lua\&.c'\fP
.br

.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBMAKE_LUA\fP"
.br
.ti -1c
.RI "#define \fBLUA_CORE\fP"
.br
.ti -1c
.RI "#define \fBLUA_LIB\fP"
.br
.ti -1c
.RI "#define \fBltable_c\fP"
.br
.ti -1c
.RI "#define \fBlvm_c\fP"
.br
.ti -1c
.RI "#define \fBLUAI_FUNC\fP   static"
.br
.ti -1c
.RI "#define \fBLUAI_DDEC\fP(def)   /* empty */"
.br
.ti -1c
.RI "#define \fBLUAI_DDEF\fP   static"
.br
.in -1c
.SH "宏定义说明"
.PP 
.SS "#define ltable_c"

.PP
在文件 onelua\&.c 第 47 行定义\&.
.SS "#define LUA_CORE"

.PP
在文件 onelua\&.c 第 45 行定义\&.
.SS "#define LUA_LIB"

.PP
在文件 onelua\&.c 第 46 行定义\&.
.SS "#define LUAI_DDEC(def)   /* empty */"

.PP
在文件 onelua\&.c 第 56 行定义\&.
.SS "#define LUAI_DDEF   static"

.PP
在文件 onelua\&.c 第 57 行定义\&.
.SS "#define LUAI_FUNC   static"

.PP
在文件 onelua\&.c 第 55 行定义\&.
.SS "#define lvm_c"

.PP
在文件 onelua\&.c 第 48 行定义\&.
.SS "#define MAKE_LUA"

.PP
在文件 onelua\&.c 第 9 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
