.TH "SemInfo" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SemInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <llex\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBlua_Number\fP \fBr\fP"
.br
.ti -1c
.RI "\fBlua_Integer\fP \fBi\fP"
.br
.ti -1c
.RI "\fBTString\fP * \fBts\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 llex\&.h 第 43 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "\fBlua_Integer\fP i"

.PP
在文件 llex\&.h 第 45 行定义\&.
.SS "\fBlua_Number\fP r"

.PP
在文件 llex\&.h 第 44 行定义\&.
.SS "\fBTString\fP* ts"

.PP
在文件 llex\&.h 第 46 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
