.TH "SParser" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SParser
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBZIO\fP * \fBz\fP"
.br
.ti -1c
.RI "\fBMbuffer\fP \fBbuff\fP"
.br
.ti -1c
.RI "\fBDyndata\fP \fBdyd\fP"
.br
.ti -1c
.RI "const char * \fBmode\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 ldo\&.c 第 768 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "\fBMbuffer\fP buff"

.PP
在文件 ldo\&.c 第 770 行定义\&.
.SS "\fBDyndata\fP dyd"

.PP
在文件 ldo\&.c 第 771 行定义\&.
.SS "const char* mode"

.PP
在文件 ldo\&.c 第 772 行定义\&.
.SS "const char* name"

.PP
在文件 ldo\&.c 第 773 行定义\&.
.SS "\fBZIO\fP* z"

.PP
在文件 ldo\&.c 第 769 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
