.TH "str_Writer" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
str_Writer
.SH SYNOPSIS
.br
.PP
.SS "成员变量"

.in +1c
.ti -1c
.RI "int \fBinit\fP"
.br
.ti -1c
.RI "\fBluaL_Buffer\fP \fBB\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lstrlib\&.c 第 215 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "\fBluaL_Buffer\fP B"

.PP
在文件 lstrlib\&.c 第 217 行定义\&.
.SS "int init"

.PP
在文件 lstrlib\&.c 第 216 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
