.TH "stringtable" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stringtable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lstate\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBTString\fP ** \fBhash\fP"
.br
.ti -1c
.RI "int \fBnuse\fP"
.br
.RI "number of elements "
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c
.SH "详细描述"
.PP 
hash table for strings 
.PP
\fB待办事项\fP
.RS 4

.RE
.PP

.PP
在文件 lstate\&.h 第 161 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "\fBTString\fP** hash"

.PP
在文件 lstate\&.h 第 162 行定义\&.
.SS "int nuse"

.PP
number of elements 
.PP
在文件 lstate\&.h 第 163 行定义\&.
.SS "int size"

.PP
在文件 lstate\&.h 第 164 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
