.TH "Table" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Table
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lobject\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBCommonHeader\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBflags\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBlsizenode\fP"
.br
.ti -1c
.RI "unsigned int \fBalimit\fP"
.br
.ti -1c
.RI "\fBTValue\fP * \fBarray\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBnode\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBlastfree\fP"
.br
.ti -1c
.RI "struct \fBTable\fP * \fBmetatable\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBgclist\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lobject\&.h 第 711 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "unsigned int alimit"

.PP
在文件 lobject\&.h 第 715 行定义\&.
.SS "\fBTValue\fP* array"

.PP
在文件 lobject\&.h 第 716 行定义\&.
.SS "CommonHeader"

.PP
在文件 lobject\&.h 第 712 行定义\&.
.SS "\fBlu_byte\fP flags"

.PP
在文件 lobject\&.h 第 713 行定义\&.
.SS "\fBGCObject\fP* gclist"

.PP
在文件 lobject\&.h 第 720 行定义\&.
.SS "\fBNode\fP* lastfree"

.PP
在文件 lobject\&.h 第 718 行定义\&.
.SS "\fBlu_byte\fP lsizenode"

.PP
在文件 lobject\&.h 第 714 行定义\&.
.SS "struct \fBTable\fP* metatable"

.PP
在文件 lobject\&.h 第 719 行定义\&.
.SS "\fBNode\fP* node"

.PP
在文件 lobject\&.h 第 717 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
