.TH "TString" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TString
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lobject\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBCommonHeader\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBextra\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBshrlen\fP"
.br
.ti -1c
.RI "unsigned int \fBhash\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   size_t \fBlnglen\fP"
.br
.ti -1c
.RI "   struct \fBTString\fP * \fBhnext\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.ti -1c
.RI "char \fBcontents\fP [1]"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lobject\&.h 第 361 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "CommonHeader"

.PP
在文件 lobject\&.h 第 362 行定义\&.
.SS "char contents[1]"

.PP
在文件 lobject\&.h 第 370 行定义\&.
.SS "\fBlu_byte\fP extra"

.PP
在文件 lobject\&.h 第 363 行定义\&.
.SS "unsigned int hash"

.PP
在文件 lobject\&.h 第 365 行定义\&.
.SS "struct \fBTString\fP* hnext"

.PP
在文件 lobject\&.h 第 368 行定义\&.
.SS "size_t lnglen"

.PP
在文件 lobject\&.h 第 367 行定义\&.
.SS "\fBlu_byte\fP shrlen"

.PP
在文件 lobject\&.h 第 364 行定义\&.
.SS "union { \&.\&.\&. }  u"


.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
