.TH "Udata" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Udata
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lobject\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBCommonHeader\fP"
.br
.ti -1c
.RI "unsigned short \fBnuvalue\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.ti -1c
.RI "struct \fBTable\fP * \fBmetatable\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBgclist\fP"
.br
.ti -1c
.RI "\fBUValue\fP \fBuv\fP [1]"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lobject\&.h 第 436 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "CommonHeader"

.PP
在文件 lobject\&.h 第 437 行定义\&.
.SS "\fBGCObject\fP* gclist"

.PP
在文件 lobject\&.h 第 441 行定义\&.
.SS "size_t len"

.PP
在文件 lobject\&.h 第 439 行定义\&.
.SS "struct \fBTable\fP* metatable"

.PP
在文件 lobject\&.h 第 440 行定义\&.
.SS "unsigned short nuvalue"

.PP
在文件 lobject\&.h 第 438 行定义\&.
.SS "\fBUValue\fP uv[1]"

.PP
在文件 lobject\&.h 第 442 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
