.TH "Udata0" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Udata0
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lobject\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBCommonHeader\fP"
.br
.ti -1c
.RI "unsigned short \fBnuvalue\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.ti -1c
.RI "struct \fBTable\fP * \fBmetatable\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBLUAI_MAXALIGN\fP"
.br
.ti -1c
.RI "} \fBbindata\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lobject\&.h 第 455 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "union { \&.\&.\&. }  bindata"

.SS "CommonHeader"

.PP
在文件 lobject\&.h 第 456 行定义\&.
.SS "size_t len"

.PP
在文件 lobject\&.h 第 458 行定义\&.
.SS "LUAI_MAXALIGN"

.PP
在文件 lobject\&.h 第 460 行定义\&.
.SS "struct \fBTable\fP* metatable"

.PP
在文件 lobject\&.h 第 459 行定义\&.
.SS "unsigned short nuvalue"

.PP
在文件 lobject\&.h 第 457 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
