.TH "Upvaldesc" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Upvaldesc
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lobject\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBTString\fP * \fBname\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBinstack\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBidx\fP"
.br
.ti -1c
.RI "\fBlu_byte\fP \fBkind\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lobject\&.h 第 490 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "\fBlu_byte\fP idx"

.PP
在文件 lobject\&.h 第 493 行定义\&.
.SS "\fBlu_byte\fP instack"

.PP
在文件 lobject\&.h 第 492 行定义\&.
.SS "\fBlu_byte\fP kind"

.PP
在文件 lobject\&.h 第 494 行定义\&.
.SS "\fBTString\fP* name"

.PP
在文件 lobject\&.h 第 491 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
