.TH "Value" 3 "2020年 九月 9日 星期三" "Version 1.0" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Value
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lobject\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "struct \fBGCObject\fP * \fBgc\fP"
.br
.ti -1c
.RI "void * \fBp\fP"
.br
.ti -1c
.RI "\fBlua_CFunction\fP \fBf\fP"
.br
.ti -1c
.RI "\fBlua_Integer\fP \fBi\fP"
.br
.ti -1c
.RI "\fBlua_Number\fP \fBn\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lobject\&.h 第 47 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "\fBlua_CFunction\fP f"

.PP
在文件 lobject\&.h 第 50 行定义\&.
.SS "struct \fBGCObject\fP* gc"

.PP
在文件 lobject\&.h 第 48 行定义\&.
.SS "\fBlua_Integer\fP i"

.PP
在文件 lobject\&.h 第 51 行定义\&.
.SS "\fBlua_Number\fP n"

.PP
在文件 lobject\&.h 第 52 行定义\&.
.SS "void* p"

.PP
在文件 lobject\&.h 第 49 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
