.TH "Vardesc" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vardesc
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lparser\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBTValuefields\fP"
.br
.ti -1c
.RI "   \fBlu_byte\fP \fBkind\fP"
.br
.ti -1c
.RI "   \fBlu_byte\fP \fBsidx\fP"
.br
.ti -1c
.RI "   short \fBpidx\fP"
.br
.ti -1c
.RI "   \fBTString\fP * \fBname\fP"
.br
.ti -1c
.RI "} \fBvd\fP"
.br
.ti -1c
.RI "\fBTValue\fP \fBk\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lparser\&.h 第 95 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "\fBTValue\fP k"

.PP
在文件 lparser\&.h 第 103 行定义\&.
.SS "\fBlu_byte\fP kind"

.PP
在文件 lparser\&.h 第 98 行定义\&.
.SS "\fBTString\fP* name"

.PP
在文件 lparser\&.h 第 101 行定义\&.
.SS "short pidx"

.PP
在文件 lparser\&.h 第 100 行定义\&.
.SS "\fBlu_byte\fP sidx"

.PP
在文件 lparser\&.h 第 99 行定义\&.
.SS "TValuefields"

.PP
在文件 lparser\&.h 第 97 行定义\&.
.SS "struct { \&.\&.\&. }  vd"


.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
