.TH "Zio" 3 "2020年 九月 8日 星期二" "Lua_Docmention" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zio
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lzio\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "size_t \fBn\fP"
.br
.ti -1c
.RI "const char * \fBp\fP"
.br
.ti -1c
.RI "\fBlua_Reader\fP \fBreader\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "\fBlua_State\fP * \fBL\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 lzio\&.h 第 55 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "void* data"

.PP
在文件 lzio\&.h 第 59 行定义\&.
.SS "\fBlua_State\fP* L"

.PP
在文件 lzio\&.h 第 60 行定义\&.
.SS "size_t n"

.PP
在文件 lzio\&.h 第 56 行定义\&.
.SS "const char* p"

.PP
在文件 lzio\&.h 第 57 行定义\&.
.SS "\fBlua_Reader\fP reader"

.PP
在文件 lzio\&.h 第 58 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Lua_Docmention 的 源代码自动生成\&.
